services:
  mariadb:
    container_name: order_and_pay_mariadb
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: ORDER_AND_PAY_DEV
    ports:
      - 3306:3306
    volumes:
      - order_and_pay_mariadb:/var/lib/mysql

#  postgres:
#    container_name: order_and_pay_postgres
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: test
#      POSTGRES_DB: order_and_pay
#    ports:
#      - 5432:5432
#    volumes:
#      - order_and_pay_postgres:/var/lib/postgresql

volumes:
  order_and_pay_mariadb:
#  order_and_pay_postgres: