services:
  user_db:
    container_name: user_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user_user_db
      POSTGRES_PASSWORD: password_user_db
      POSTGRES_DB: user_db
    ports:
      - "5440:5432"
    volumes:
      - user_db:/var/lib/postgresql

  order_db:
    container_name: order_db
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: user_order_db
      POSTGRES_PASSWORD: password_order_db
      POSTGRES_DB: order_db
    ports:
      - "5441:5432"
    volumes:
      - order_db:/var/lib/postgresql

  payment_db:
    container_name: payment_db
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: user_payment_db
      POSTGRES_PASSWORD: password_payment_db
      POSTGRES_DB: payment_db
    ports:
      - "5442:5432"
    volumes:
      - payment_db:/var/lib/postgresql

  delivery_db:
    container_name: delivery_db
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: user_delivery_db
      POSTGRES_PASSWORD: password_delivery_db
      POSTGRES_DB: delivery_db
    ports:
      - "5443:5432"
    volumes:
      - delivery_db:/var/lib/postgresql

  restaurant_db:
    container_name: restaurant_db
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: user_restaurant_db
      POSTGRES_PASSWORD: password_restaurant_db
      POSTGRES_DB: restaurant_db
    ports:
      - "5444:5432"
    volumes:
      - restaurant_db:/var/lib/postgresql

  kafka_1:
    container_name: kafka_1
    restart: always
    image: confluentinc/cp-kafka:7.8.3
    ports:
      - "9191:9092"
    environment:
      CLUSTER_ID: kafka-order-and-pay-id-1

      KAFKA_NODE_ID: 1
      KAFKA_KRAFT_MODE: true
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka_1:9191,2@kafka_2:9192,3@kafka_3:9193

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9191
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2

      KAFKA_LOG_DIRS: /var/lib/kafka/data

    volumes:
      - kafka_1:/var/lib/kafka/data

  kafka_2:
    container_name: kafka_2
    restart: always
    image: confluentinc/cp-kafka:7.8.3
    ports:
      - "9192:9092"
    environment:
      CLUSTER_ID: kafka-order-and-pay-id-1

      KAFKA_NODE_ID: 2
      KAFKA_KRAFT_MODE: true
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka_1:9191,2@kafka_2:9192,3@kafka_3:9193

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9192
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2

      KAFKA_LOG_DIRS: /var/lib/kafka/data

    volumes:
      - kafka_2:/var/lib/kafka/data

  kafka_3:
    container_name: kafka_3
    restart: always
    image: confluentinc/cp-kafka:7.8.3
    ports:
      - "9193:9092"
    environment:
      CLUSTER_ID: kafka-order-and-pay-id-1

      KAFKA_NODE_ID: 3
      KAFKA_KRAFT_MODE: true
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka_1:9191,2@kafka_2:9192,3@kafka_3:9193

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9193
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2

      KAFKA_LOG_DIRS: /var/lib/kafka/data

    volumes:
      - kafka_3:/var/lib/kafka/data

volumes:
  order_and_pay_mariadb:
  user_db:
  order_db:
  payment_db:
  delivery_db:
  restaurant_db:
  kafka_1:
  kafka_2:
  kafka_3:
