### GET request to example server
POST http://localhost:5454/api/v1/restaurants/orders/preparing
Content-type: application/json

{
  "orderId":"34403b42-ea61-494b-9a10-0354e4a182e1",
  "restaurantId": "3c5a88e2-ff5b-44a7-8d7c-0e6f6a9fbd11"
}

###
POST http://localhost:5454/api/v1/restaurants/orders/ready-for-delivery
Content-type: application/json

{
  "orderId":"34403b42-ea61-494b-9a10-0354e4a182e1",
  "restaurantId": "3c5a88e2-ff5b-44a7-8d7c-0e6f6a9fbd11"
}
