### GET request to example server
POST http://localhost:5454/api/v1/restaurants/orders/preparing
Content-type: application/json

{
  "orderId":"cba02d1c-0f39-4e42-87ac-88f9ad52acee",
  "restaurantId": "3c5a88e2-ff5b-44a7-8d7c-0e6f6a9fbd11"
}

###
POST http://localhost:5454/api/v1/restaurants/orders/ready-for-delivery
Content-type: application/json

{
  "orderId":"cba02d1c-0f39-4e42-87ac-88f9ad52acee",
  "restaurantId": "3c5a88e2-ff5b-44a7-8d7c-0e6f6a9fbd11"
}
