spring:
  application:
    name: 'order_and_pay'

  profiles:
    active: 'dev'

#springdoc:
#  api-docs:
#    path: '/api/docs'

springdoc:
  swagger-ui:
    path: /api/v1
#  springdoc.api-docs.path=/api-docs

server:
  port: 2000


