
spring:
  config:
    activate:
      on-profile: 'dev'

  datasource:
    url: ${DEV_MARIADB_URL}
    username: ${DEV_USER}
    password: ${DEV_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

logging:
  level:
    org.springframework: DEBUG


