
spring:
  config:
    activate:
      on-profile: 'dev'

  datasource:
    url: ${DEV_MARIADB_URL}
    username: ${DEV_USER}
    password: ${DEV_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org.springframework: INFO


