###
GET http://localhost:2000/users
###

POST http://localhost:2000/users/register
Content-Type: application/json

{
  "username": "harold",
  "firstName": "Harold",
  "lastName": "Raj",
  "password": "password",
  "email": "harold.raj@ecole-it.com",
  "birthDate": "2000-05-20"
}
