spring:
  application:
    name: 'order-and-pay-restaurant-service'

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://localhost:5444/restaurant_db
    username: user_restaurant_db
    password: password_restaurant_db

  kafka:
    bootstrap-servers: localhost:9191

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: restaurant-group

    properties:
      spring:
        json:
          trusted:
            packages: "com.hrajaona.*"

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 5454

logging:
  level:
    org.springframework: INFO